version: '2.2'
services:
  arweave:
    build:
      context: arweave
      args:
        ERLC_OPTS: "-DFIXED_DIFF=4 -DFIXED_DELAY=0"
    ports:
      - "1984:1984"
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "echo ADECEEQHldVB55AQRg6cq_hhFGKnJiVKN0pRuvp3Sms,1000000 > data/genesis_wallets.csv && ./docker-arweave-server no_auto_join init mine"
    cpus: 0.5
  arweave-peer:
    depends_on:
      - arweave
    build:
      context: arweave
      args:
        ERLC_OPTS: "-DFIXED_DIFF=4 -DFIXED_DELAY=0"
    ports:
      - "1985:1984"
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "./docker-arweave-server peer $$(getent hosts arweave | cut -d' ' -f1)"
  it:
    build:
      context: .
      dockerfile: docker/sbt.dockerfile
    command: ["it:testOnly -- -F 20.0"]
    depends_on:
      - arweave
      - arweave-peer
    environment:
      TESTNET_HOST: http://arweave:1984
