version: '2.2'
services:
  arweave-seed:
    build:
      context: arweave
      args:
        ERLC_OPTS: "-DFIXED_DIFF=8"
    ports:
      - "1985:1984"
    command: no_auto_join init mine peer 127.0.0.1:9
    cpus: 0.5
  arweave:
    depends_on:
      - arweave-seed
    build:
      context: arweave
      args:
        ERLC_OPTS: "-DFIXED_DIFF=8"
    ports:
      - "1984:1984"
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "./arweave-server peer $$(getent hosts arweave-seed | cut -d' ' -f1)"
  it:
    build:
      context: .
      dockerfile: docker/sbt.dockerfile
    command: ["it:testOnly -- -F $SPAN_SCALE_FACTOR"]
    depends_on:
      - arweave
    environment:
      TESTNET_HOST: arweave
