version: '3'
services:
  arweave:
    build: docker/arweave
    ports:
      - "1984:1984"
    command: no_auto_join init mine peer 127.0.0.1:9
  it:
    build:
      context: .
      dockerfile: docker/sbt.dockerfile
    command: it:test
    depends_on:
      - arweave
