#!/bin/sh

set -o errexit

make --quiet

ADDRESS=
HOST=$ARWEAVE_NODE
while getopts "a:h:" opt; do
    case $opt in
        a) ADDRESS="$OPTARG" ;;
        h) HOST="$OPTARG" ;;
        \?) echo "Invalid option: -$OPTARG" >&2
            exit 2 ;;
    esac
done

${DOCKER-docker} run --rm \
    arweave-scripts \
    balance --address "$ADDRESS" --host "$HOST"
