#!/bin/sh

set -o errexit

make --quiet

WALLET=
TO=
QUANTITY=
HOST=$ARWEAVE_NODE
while getopts "t:w:q:h:" opt; do
    case $opt in
        w) WALLET="$OPTARG" ;;
        t) TO="$OPTARG" ;;
        q) QUANTITY="$OPTARG" ;;
        h) HOST="$OPTARG" ;;
        \?) echo "Invalid option: -$OPTARG" >&2
            exit 2 ;;
    esac
done

case "$(uname -s)" in
    Linux) wallet_fn=$(readlink -f "$WALLET" || echo "$WALLET");;
    Darwin) wallet_fn=$(readlink "$WALLET" || echo "$(pwd)/$WALLET");;
esac

${DOCKER-docker} run \
    -v $wallet_fn:/wallet.json:ro \
    --rm \
    arweave-scripts transfer \
    --to "$TO" \
    --quantity "$QUANTITY" \
    --host "$HOST" \
    --wallet /wallet.json
