#!/bin/sh

set -o errexit
set -o xtrace

make --quiet

WALLET=
TO=
QUANTITY=
HOST=$ARWEAVE_NODE
while getopts "t:w:q:h:" opt; do
    case $opt in
        w) WALLET="$OPTARG" ;;
        t) TO="$OPTARG" ;;
        q) QUANTITY="$OPTARG" ;;
        h) HOST="$OPTARG" ;;
        \?) echo "Invalid option: -$OPTARG" >&2
            exit 2 ;;
    esac
done

${DOCKER-docker} run \
    -v $(readlink -f "$WALLET"):/wallet.json:ro \
    --rm \
    arweave-scripts transfer \
    --to "$TO" \
    --quantity "$QUANTITY" \
    --host "$HOST" \
    --wallet /wallet.json
